### ISSUE TITLE
Home page improvements 

### ISSUE THREAD

**Issue by UdaySagar-Git** [WebWizards-Git/studysphere#26]
in home page 
![image](https://github.com/WebWizards-Git/studysphere/assets/111575806/aa1df62f-d9bb-4081-9d54-f5911533191e)

- [x] Display quiz submission time , leaderboard rank / total members taken
- [x] Add followers and following count , friends.length , friendsof.length

![image](https://github.com/WebWizards-Git/studysphere/assets/156537424/1d121c35-a9f8-432c-b72b-63ea32396937)

- [x] messaging directly when friends (a message icon at existing friends column)

**Comment by vighnesh-7** [comment]
leaderboard rank cant be implemented
